FROM nvidia/cuda:10.1-cudnn7-devel-ubuntu16.04


# base
RUN apt update --yes
RUN apt install --yes --no-install-recommends vim
RUN apt install --yes --no-install-recommends git
RUN apt install --yes --no-install-recommends ssh
RUN apt install --yes --no-install-recommends sudo
RUN apt install --yes --no-install-recommends wget

ENV __USER__=ddd
ENV __HOME__=/home/$__USER__
ENV __PRROFILE__=$__HOME__/.bashrc
RUN echo '<KEY/>\n<KEY/>' | passwd
RUN echo '<KEY/>\n<KEY/>' | adduser $__USER__
RUN echo "$__USER__ ALL=(ALL:ALL) ALL" >> /etc/sudoers

ENV __TMP__=/etc/ssh/ssh_config
RUN cat $__TMP__ | grep -v ServerAliveInterval | tee ${__TMP__}_
RUN mv ${__TMP__}_ $__TMP__
RUN echo ServerAliveInterval 60 | tee -a $__TMP__


# cuda
RUN apt install --yes --no-install-recommends libnvinfer6=6.0.1-1+cuda10.1
RUN apt install --yes --no-install-recommends libnvinfer-dev=6.0.1-1+cuda10.1
RUN apt install --yes --no-install-recommends \
    libnvinfer-plugin6=6.0.1-1+cuda10.1
ENV __TMP__=/usr/local/cuda/compat:\$LD_LIBRARY_PATH
RUN echo export LD_LIBRARY_PATH=$__TMP__ >> $__PRROFILE__
ENV __TMP__=/usr/local/cuda/extras/CUPTI/lib64:\$LD_LIBRARY_PATH
RUN echo export LD_LIBRARY_PATH=$__TMP__ >> $__PRROFILE__
RUN echo export PATH=/usr/local/cuda/bin:\$PATH >> $__PRROFILE__


# python
RUN apt install --yes --no-install-recommends python3-dev
RUN apt install --yes --no-install-recommends python3-pip
RUN ln --symbolic $( which python3 ) /usr/bin/python
RUN ln --symbolic $( which pip3 ) /usr/bin/pip
RUN echo export PATH=\$HOME/.local/bin:\$PATH >> $__PRROFILE__


# bash
RUN wget https://ftp.gnu.org/gnu/bash/bash-4.4.tar.gz
RUN tar --extract --verbose --file bash-4.4.tar.gz
RUN cd bash-4.4 && ./configure && make && make install
RUN rm -r bash-4.4*


RUN apt autoremove --yes


USER $__USER__
WORKDIR $__HOME__


# python
ENV PATH=$__HOME__/.local/bin:$PATH
RUN pip install --upgrade pip 
RUN pip install --upgrade setuptools
RUN pip install --upgrade pandas
RUN pip install --upgrade pylint
RUN pip install --upgrade jupyter
RUN pip install --upgrade matplotlib
RUN pip install --upgrade tensorflow
RUN pip install --upgrade pyinstaller


# node
ENV __DNAME__=node
ENV __VER__=12.16.1
ENV __NAME__=node-v$__VER__-linux-x64.tar.xz
ENV __URL__=https://nodejs.org/dist/v$__VER__/$__NAME__
RUN wget $__URL__
RUN tar --extract --verbose --file $__NAME__
RUN rm $__NAME__
RUN mv ${__NAME__%.tar.xz} $__DNAME__
RUN echo export PATH=\$HOME/$__DNAME__/bin:\$PATH >> $__PRROFILE__

ENV PATH=$__HOME__/$__DNAME__/bin:$PATH
RUN npm install --global npm
RUN npm install --global @angular/cli
